image:
  repository: friendica
  pullPolicy: IfNotPresent
  tag: 2023.05@sha256:c36ca393f4073a95ee575cc875b1824418108f9809a992a3fcb8d45d503e4ab5
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/ping"
            readiness:
              path: "/ping"
            startup:
              path: "/ping"
          env:
            MYSQL_USER: "{{ .Values.mariadb.mariadbUsername }}"
            MYSQL_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
            MYSQL_PORT: 3306
            REDIS_PORT: 6379
            REDIS_DB: 1
            FRIENDICA_TZ: "{{ .Values.TZ }}"
            FRIENDICA_DATA_DIR: "/data"
            FRIENDICA_CONFIG_DIR: "/config"
            # User Defined
            FRIENDICA_ADMIN_MAIL: "my@domain.com"
            FRIENDICA_URL: "http://localhost:{{ .Values.service.main.ports.main.port }}"
            FRIENDICA_UPGRADE: false
            FRIENDICA_SITENAME: ""
            PHP_MEMORY_LIMIT: "512M"
            PHP_UPLOAD_LIMIT: "512M"
            MYSQL_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            MYSQL_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: mariadb-password
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PW:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: redis-password
service:
  main:
    ports:
      main:
        port: 10058
        targetPort: 80
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
redis:
  enabled: true
mariadb:
  enabled: true
  mariadbUsername: friendica
  mariadbDatabase: friendica
portal:
  open:
    enabled: true
