image:
  repository: linuxserver/mylar3
  tag: version-v0.7.6@sha256:1fc63855522a99e3d8a8e1c32c9930e3e516ad36b5a74ea092a83d18b85d14cd
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
